# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:7001/api/Customers/GetAll

###

GET https://localhost:7001/api/Customers/Get/1

###

POST https://localhost:7001/api/Customers/Add
Content-Type: application/json

{
    "Name": "Item name",
    "Category": "Food",
    "Quantity": 10
}

###

PATCH https://localhost:7001/api/Customers/Update
Content-Type: application/json

{
    "Id": 1,
    "Name": "Item name",
    "Category": "Food",
    "Quantity": 10
}

###

DELETE https://localhost:7001/api/Customers/Delete/1
