# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:7001/api/Customers/GetAll

###

GET https://localhost:7001/api/Customers/Get/1

###

POST https://localhost:7001/api/Customers/Add
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com"
}

###

PATCH https://localhost:7001/api/Customers/Update
Content-Type: application/json

{
    "id": 123,
    "name": "Updated Name",
    "email": "updated@example.com"
}

###

DELETE https://localhost:7001/api/Customers/Delete?id=123
