// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using backend.api.Models.Configurations;
using backend.api.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace backend.api.Models;

public partial class fullstackdbContext : DbContext
{
    public fullstackdbContext(DbContextOptions<fullstackdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> People { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.PersonConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
