USE [master]
GO

/****** Object:  Database [FullstackDB]    Script Date: 6/25/2024 12:44:16 AM ******/
CREATE DATABASE [FullstackDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Person', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.FULLSTACKSERVER\MSSQL\DATA\Person.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Person_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.FULLSTACKSERVER\MSSQL\DATA\Person_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FullstackDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FullstackDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FullstackDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FullstackDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FullstackDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FullstackDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [FullstackDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FullstackDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FullstackDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FullstackDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FullstackDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FullstackDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FullstackDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FullstackDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FullstackDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FullstackDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FullstackDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FullstackDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FullstackDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FullstackDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FullstackDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FullstackDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FullstackDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FullstackDB] SET RECOVERY FULL 
GO

ALTER DATABASE [FullstackDB] SET  MULTI_USER 
GO

ALTER DATABASE [FullstackDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FullstackDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FullstackDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FullstackDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FullstackDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FullstackDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FullstackDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [FullstackDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [FullstackDB] SET  READ_WRITE 
GO


